name: Build unypkg Base System

on: workflow_dispatch

jobs:
  build-unypkg-system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo -i
      - run: chmod +x unypkg-base-build.sh
      - run: ./unypkg-base-build.sh
        env:
          UNY_AUTO_PAT: ${{ secrets.UNY_AUTO_PAT }}
